### ISSUE TITLE
Reintroduce support for 82574L

### ISSUE THREAD

**Issue by Paktosan** [Mieze/IntelMausiEthernet#14]
This chip was working with AppleIntelE1000e but does not with IntelMausi. You wrote that you removed support for older chips but I still consider this chip relevant and recent since it is not deprecated by Intel and there are still cards produced. For example I have one of this cards that was produced in September last year. Thanks in advance!

**Comment by Mieze** [comment]
I'm sorry but I'm not going to waste my time with the old 82574L because
1. it's junk silicon which makes driver programming a pain.
2. there is an Apple provided driver for that chip (injector kext needed).
3. IntelMausiEthernet is open source and everybody is free to modify it according to his/her needs.
