### ISSUE TITLE
Maybe some literature/howto on porting from Linux?

### ISSUE THREAD

**Issue by jafd** [Mieze/IntelMausiEthernet#2]
First, thanks for the hard work! (I'm a happy user of your kext.)

Second, more of a "feature request" of sort: maybe put together a guide on porting drivers from Linux (BSD kernel code is more straightforward), and list some caveats, so that other developers might want to try to dive in with more device drivers.

For example, I'm trying to wrap my head around the fact that you carry Apple header files around, instead of relying on what SDK provides. Isn't it a bit on the dangerous side? There sure was some reasoning behind this decision.

Even if you are not terribly inclined to make a guide proper (understandable — it's a lot of effort), even assorted napkin notes could be of immense help. I'm trying to dive with porting something myself, and find it hard to gather necessary information, having to read more code than I usually like to.

Thanks again!

**Comment by ahyattdev** [comment]
This would be so helpful. Any resources would be awesome.

**Comment by Mieze** [comment]
Well, unfortunately there isn't much documentation I could recommend. Besides the general I/O Kit documentation, I found Apple's "Porting drivers to OS X" helpful.

https://developer.apple.com/library/mac/documentation/Porting/Conceptual/PortingDrivers/intro/intro.html

Another important source of information is OS X source code which can be obtained at:

http://opensource.apple.com

The reason why the project contains Apple header files is because the aren't part of the official SDK but part of IONetworking.kext's source code and they are crucial in order to use Apple's new private network driver interface which improves cooperation with power management as well as with virtualization software like VMware.
