### ISSUE TITLE
V2.5.0 not working with I217V

### ISSUE THREAD

**Issue by gazzmanzx6** [Mieze/IntelMausiEthernet#28]
The latest version is not working on my Gigabyte Z87X-UD4H motherboard under MacOS Mojave.
Version 2.4.0 works fine.
Has something changed in the latest version?
Is there a way to check what is wrong?

Thanks.

**Comment by MacNB** [comment]
@gazzmanzx6, you have not provided any logs of "is not working".
What boot loader were you using ?
What makes you think it's not working ?

**Comment by gazzmanzx6** [comment]
@MacNB See the linked post #29 this appears to be the same issue. That’s why I linked to it.

**Comment by MacNB** [comment]
@gazzmanzx6 #29 is the one I raised :)
There, I gave a specific error and from a log file that shows that this kext is not injected by OpenCore. 
Your issue just states "The latest version is not working on my Gigabyte Z87X-UD4H" without any logs of what is the issue. There's no connection with your problem and the one I am seeing.
That is why I asked you to report which boot loader were you using and show logs that may help the author understand your problem.

If your logs show the same error as mine, then the problems are linked (maybe) but since you have not posted your errors the author cannot be sure it's the same problem. 

I hope I made my self clear.

**Comment by gazzmanzx6** [comment]
@MacNB That is why I asked how to check what is wrong. I don’t know where to look for logs as I am new to OpenCore.

**Comment by MacNB** [comment]
Ah ok. First of all you need to explain what happens when you say "it is not working". Which you have not explained (e.g. what's not working ? just LAN or macOS ?)

There two version of OpenCore ([original](https://www.insanelymac.com/forum/topic/338516-opencore-discussion/) and [NDK](https://www.insanelymac.com/forum/topic/341402-customized-opencore-with-additional-features/) fork). 
Then go to the correct forum on the links above and clearly explain your problem there.
You will need : your motherboard details, what works and what does not work.

BTW, the log file is on the root of the EFI partition (a file with .txt extension)

**Comment by nyhtml** [comment]
It's broken in Clover too.


Fixed it by doing Show Package Contents and replacing all files in MacOS with that from an older copy. Now when I check for updates with the configurator,  I won't accidentally overwrite it again.

**Comment by MacNB** [comment]
> It's broken in Clover too.
> 
> Fixed it by doing Show Package Contents and replacing all files in MacOS with that from an older copy. Now when I check for updates with the configurator, I won't accidentally overwrite it again.

Huh???. There's no point in "replacing all files in MacOS from an older copy" as you might as well use the older kext.

**Comment by Mieze** [comment]
Version 2.5.0 is working fine with I217V as is is my my test configuration. In case you have any problem, fix your system because it's definitely not the driver which causes the problem.
