### ISSUE TITLE
Ipv6 interface addresses not avail. after sleep

### ISSUE THREAD

**Issue by th0u** [Mieze/IntelMausiEthernet#30]
Hello,
I use the latest driver in an OC 0.5.7/Caltalina 10.15.4 environment on a GB B360M D3H.
Unfortunately ipv6 adresses on the intel Onboard Nic are not available after sleep/wake.
ifconfig down / up or reboot resolves the problem.
Due to another win10/macOS dual boot issue, I installed a Realtek 8168 PCIE Adapter using your RTL8111 kext. 
The interface provided by the Realtek card does not lose its ipv6 addresses after sleep/wake.
I also tested with some USB-NICs: ipv6 addresses are not lost after sleep/wake.

I am not sure if it is a driver issue or something else. It may also be an issue because the Intel NIC is an Onboard Nic.
Well, if you think that is something to look at, I am happy to provide more details.
Kind regards, T

**Comment by A1bi** [comment]
I've been experiencing the exact same issue ever since I built my machine (~ 1.5 years ago). I have a **Gigabyte H370M DS3H** board. I don't see any IPv6 traffic in Wireshark after I wake the system, especially no Router Solicitations or DHCPv6 requests.

I created a workaround by using [ControlPlane](https://github.com/dustinrue/ControlPlane) which will run a simple `networksetup -setv6off Ethernet && networksetup -setv6automatic Ethernet` every time my system wakes from sleep. Toggling IPv6 on the interface is enough to bring it back.

I too can confirm that this problem does not occur with other network interfaces which in my case is a WiFi card using the native Apple driver.

**Comment by extric99** [comment]
I have the exact same issue on a Gigabyte Gaming X using the 2.5.0d141.4.5 version of the kext on Catalina 10.15.5

**Comment by A1bi** [comment]
I, too, am happy to report that the issue has been resolved for me. I finally switched from Clover to OpenCore and redid my whole setup from scratch (config.plist, kexts, SSDTs) which I didn't do with Clover before (I used a config I found in a forum).

But the work absolutely paid off. This and several other issues are now gone. I'm pretty sure this issue is not a bug in IntelMausiEthernet but was rather a result of my half-assed Clover configuration.

I'm still on Catalina by the way.
