### ISSUE TITLE
Can't Upgrade from 2.4.1d1 to 2.5.3d1 Ethernet stops working

### ISSUE THREAD

**Issue by cyberfunk** [Mieze/IntelMausiEthernet#38]
Originally using Rehabmans clover guide and scripts to get my HP EliteBook 820 G4 working with Clover and Mojave. 

https://www.tonymacx86.com/threads/guide-hp-probook-elitebook-zbook-using-clover-uefi-hotpatch.261719/ 

The Rehabman guide is out of date but everything still works with some of the outdated kexts his scripts pull. When I update InternetMausiEthernet.kext manually using Kext Updater to the latest version my Ethernet stops working and the ethernet card is no longer recognized in Network preferences. (The same happens when I update VoodooPS2Controller.kext to the latest. The trackpad and buttons stop working) I'm also using an old version of clover 5122 pre OpenCore quirks if that helps.

**Comment by nyhtml** [comment]
Try [IntelMausi](https://github.com/acidanthera/IntelMausi) or downgrade to an older version of IntelMausiEthernet. It's possible the SMC next is the cause. My AppleALC stopped and when a switched from FakeSMC to VirtualSMC, it started to work again.

**Comment by cyberfunk** [comment]
Thanks. I downgraded everything back so I guess I just have to stick to the older versions for now.

**Comment by Mieze** [comment]
Read the instructions and fix your system! I know you haven't because in case you had, you wouldn't post here. The problem is located in front of the computer, not in the driver.

**Comment by cyberfunk** [comment]
> Read the instructions and fix your system! I know you haven't because in case you had, you wouldn't post here. The problem is located in front of the computer, not in the driver.

“The problem is located in front of the computer”.....🤔

Your outrage is misplaced. Since programs like Kext Updater pull these kexts remotely most users of apps like Kext Updater or Hackintool will never even see the instructions on this or any of your pages. I suggest you take a deep breath and think before leveling insults. We’re all in this together😄That said I will try your suggestions.

**Comment by Mieze** [comment]
You don't deserve help because you haven't done your job. If you want full service or aren't smart enough, visit the Apple Store next to you. I haven't got the time (and no motivation) to explain every detail over and over again to every brain dead user who comes around. People like you really make me want to give up sharing my code.

**Comment by Artoria2e5** [comment]
There's a neat little feature to turn that off if you want to read the GitHub instructions:
<img width="437" alt="image" src="https://user-images.githubusercontent.com/6459309/230833434-cdfba509-fcd7-4d95-9548-c48e86f18977.png">

<img width="953" alt="image" src="https://user-images.githubusercontent.com/6459309/230833405-17fba371-ca58-4973-a525-9f276aec2285.png">

or even archive. whatever.

**Comment by Mieze** [comment]
Well, maybe you should read the instructions because I always said that support requests should be made in the insanelymac.com forum whereas this here is for bug reports only. Is it so hard to distinguish between both?

Besides that, this is open source software. It's free and in case you have a claim against me, make sure it's covered by the GPL.
