### ISSUE TITLE
Crash in the driver, perhaps related to sleep wake and or heavy load

### ISSUE THREAD

**Issue by emlynmac** [Mieze/IntelMausiEthernet#8]
Driver works great for the most part, but if I leave the system with Time Machine going, it will reliably crash.

Driver version 2.2.0; OS X version 10.12.2
Card is an Intel i217V.

Crash dump:

````
*** Panic Report ***
panic(cpu 2 caller 0xffffff8014605ead): Kernel trap at 0xffffff7f97a768a7, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0xffffff820474d008, CR3: 0x000000001fa83000, CR4: 0x00000000001627e0
RAX: 0xffffff803b3da400, RBX: 0xffffff81b77ce000, RCX: 0x0000000000000000, RDX: 0x0000000000000100
RSP: 0xffffff9206e63cf0, RBP: 0xffffff9206e63d70, RSI: 0xffffff803b3d0000, RDI: 0x0000000000000000
R8:  0x0000000000000000, R9:  0xffffff81f8776068, R10: 0x0000000000000000, R11: 0xffffff81d80e5058
R12: 0xffffff81b77ce000, R13: 0xffffff803a299de8, R14: 0xffffff820474d000, R15: 0x0000000000000000
RFL: 0x0000000000010246, RIP: 0xffffff7f97a768a7, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0xffffff820474d008, Error code: 0x0000000000000000, Fault CPU: 0x2, PL: 0, VF: 1

Backtrace (CPU 2), Frame : Return Address
0xffffff9206e63980 : 0xffffff80144f211c 
0xffffff9206e63a00 : 0xffffff8014605ead 
0xffffff9206e63be0 : 0xffffff80144a3743 
0xffffff9206e63c00 : 0xffffff7f97a768a7 
0xffffff9206e63d70 : 0xffffff7f97a77232 
0xffffff9206e63d90 : 0xffffff7f95a6f9d4 
0xffffff9206e63dc0 : 0xffffff8014abf81a 
0xffffff9206e63e30 : 0xffffff7f95a6fa3b 
0xffffff9206e63e80 : 0xffffff7f95a73c7a 
0xffffff9206e63ef0 : 0xffffff801478a005 
0xffffff9206e63fb0 : 0xffffff80144a0af7 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONetworkingFamily(3.2)[6326DB88-5330-3F0C-91F6-D478AB5E7503]@0xffffff7f95a67000->0xffffff7f95a93fff
         com.insanelymac.IntelMausiEthernet(2.2)[3A6046E0-A8B1-32C2-9532-1EBF16AEB28B]@0xffffff7f97a73000->0xffffff7f97a86fff
            dependency: com.apple.iokit.IONetworkingFamily(3.2)[6326DB88-5330-3F0C-91F6-D478AB5E7503]@0xffffff7f95a67000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[6F8D3ACB-27CB-3B57-9E06-53E377762F5C]@0xffffff7f94d46000

BSD process name corresponding to current thread: kernel_task
Boot args: dart=0 
````

WoL disabled and UEFI network stack also disabled. 
I've got the source and will start digging into the why if I can.

**Comment by Mieze** [comment]
Don't waste your time searching for a bug in the source code because I'm quite sure that there is none causing this kernel panic. At least every reported kernel panic in the last 2 years has turned out to be the result of one of these reasons:
- A messed up system.
- A broken DSDT, e.g. broken interrupt routing code.
- Wrong BIOS settings, e.g. the UEFI network stack or bad power management settings interfering with the driver.

**Comment by emlynmac** [comment]
Thanks for the pointers as to where to look. The board is a DSDT-free Gigabyte GA-Z87X-UD3H, which has had no issues so far - and that's been several years of use. The original e1000 driver was not so good, so I've been using a different intel card for a while. 

Could you be more specific what you mean by 'a messed up system' and 'wrong BIOS settings'? I've followed what I read at insanelymac - disable WoL and the network stack in the BIOS. What else should I be looking for?

**Comment by Mieze** [comment]
OS X has become more and more picky about the ACPI data structures starting with El Capitan. When I set up my test machine with an Asrock H97M-Pro4 under Yosemite, the board was almost hassle-free. After upgrading to El Capitan, I got an instant kernel panic on boot with a discrete GPU installed due to broken interrupt routing functions in the DSDT and even after resolving that problem, I had random kernel panics on sleep/wake with WoL enabled in OS X. In order to solve this problem, I had to keep Thunderbolt support enabled in BIOS (who knows why???), although there is no thunderbolt hardware installed in the system, and had to rewrite about 10% of the DSDT's code in order to get it stable with WoL enabled in OS X. The Sierra upgrade resulted in a bunch of new ACPI errors in the kernel logs too so that I had to rework the DSDT again. Look for ACPI errors in the kernel logs as a starting point and try to disable WoL in System Preferences when possible.

With regard to the UEFI setup, consult your board's manual and check all options which may affect the NIC's operation, in particular the UEFI network stack, network boot and power management. I even had a case where a user needed to to enable the network stack temporarily in order to get access to an option which had to be disabled for stable operation. Some things are straightforward while others need trial and error to find out like my Thunderbolt issue. ;-)

Messed up systems usually result from things going wrong while installing new drivers and require a reinstall in order to recover from that situation. During development I had a case where any version of the driver, even older versions which used to work fine, caused the machine to crash on boot. After a reinstall, the system work fine with the driver. I even watched this happen with Apple provided drivers.

**Comment by emlynmac** [comment]
I'll see if I can get the crash to happen again - now I've got the debug version of the kext loaded.

It really doesn't happen very frequently - only twice in the last week - and it seems to be related to sleep / wake so it could be a number of things.

I'll let you know how it goes....

**Comment by billimek** [comment]
@emlynmac I've been running hackintosh for a couple of years now using the IntelMausiEthernet driver with no problems or panics at all.

Interestingly enough I got a panic today (for the first time with this and the first time on an otherwise very stable system) that looks just like yours:

```
*** Panic Report ***
panic(cpu 0 caller 0xffffff8017c05ecd): Kernel trap at 0xffffff7f983c58f3, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0xffffff802faf0008, CR3: 0x0000000020701000, CR4: 0x00000000003627e0
RAX: 0xffffff803c4a8c00, RBX: 0xffffff81b8952000, RCX: 0x0000000000000000, RDX: 0x0000000000000100
RSP: 0xffffff9204b83cf0, RBP: 0xffffff9204b83d70, RSI: 0xffffff803c4a0000, RDI: 0x0000000000000000
R8:  0x0000000000000000, R9:  0xffffff803daa82b0, R10: 0x0000000000000000, R11: 0xffffff801828a810
R12: 0xffffff81b8952000, R13: 0xffffff803b470b68, R14: 0xffffff802faf0000, R15: 0x0000000000000000
RFL: 0x0000000000010246, RIP: 0xffffff7f983c58f3, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0xffffff802faf0008, Error code: 0x0000000000000000, Fault CPU: 0x0, PL: 0, VF: 1

Backtrace (CPU 0), Frame : Return Address
0xffffff9204b83980 : 0xffffff8017af210c 
0xffffff9204b83a00 : 0xffffff8017c05ecd 
0xffffff9204b83be0 : 0xffffff8017aa3743 
0xffffff9204b83c00 : 0xffffff7f983c58f3 
0xffffff9204b83d70 : 0xffffff7f983c627e 
0xffffff9204b83d90 : 0xffffff7f983969d4 
0xffffff9204b83dc0 : 0xffffff80180bf92a 
0xffffff9204b83e30 : 0xffffff7f98396a3b 
0xffffff9204b83e80 : 0xffffff7f9839ac7a 
0xffffff9204b83ef0 : 0xffffff8017d8a025 
0xffffff9204b83fb0 : 0xffffff8017aa0af7 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONetworkingFamily(3.2)[6326DB88-5330-3F0C-91F6-D478AB5E7503]@0xffffff7f9838e000->0xffffff7f983bafff
         com.insanelymac.IntelMausiEthernet(2.2)[96D89FA5-7CA6-33AA-8A56-A5F9276E55A2]@0xffffff7f983c2000->0xffffff7f983d5fff
            dependency: com.apple.iokit.IONetworkingFamily(3.2)[6326DB88-5330-3F0C-91F6-D478AB5E7503]@0xffffff7f9838e000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[57960DC6-4099-31BC-9B47-52CD647779C7]@0xffffff7f9824f000

BSD process name corresponding to current thread: kernel_task
Boot args: dart=0 darkwake=0 nvda_drv=1 

Mac OS version:
16D32

```

**Comment by emlynmac** [comment]
I haven't seen this issue again.
